# encoding: utf-8

include ModeloQytetet::MetodoSalirCarcel
module ControladorQytetet
OpcionMenu = [:INICIARJUEGO,:JUGAR,:APLICARSORPRESA,
:INTENTARSALIRCARCELPAGANDOLIBERTAD,:INTENTARSALIRCARCELTIRANDODADO,
:COMPRARTITULOPROPIEDAD,:HIPOTECARPROPIEDAD,:CANCELARHIPOTECA,
:EDIFICARCASA,:EDIFICARHOTEL,:VENDERPROPIEDAD,:PASARTURNO,
:OBTENERRANKING,:TERMINARJUEGO,:MOSTRARJUGADORACTUAL,
:MOSTRARJUGADORES,:MOSTRARTABLERO ]
end
